animations {
    enabled = true

    # Плавный вход, быстрый выход
    bezier = soft_decel, 0.05, 0.75, 0.1, 1
    bezier = soft_accel, 0.3, 0, 0.7, 0.15

    # Окна
    animation = windows, 1, 6, soft_decel, popin 65%
    animation = windowsOut, 1, 4, soft_accel, popin 65%



    # Границы и прозрачность
    animation = border, 1, 8, default
    animation = fade, 1, 6, default

    # Рабочие пространства
    animation = workspaces, 1, 7, soft_decel, slide
    animation = specialWorkspace, 1, 7, soft_decel, slidevert
}
