hl.config({ animations = { enabled = true } })
hl.curve("soft_decel", { type = "bezier", points = { { 0.05, 0.75 }, { 0.1, 1 } } })
hl.curve("soft_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.7, 0.15 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 6, bezier = "soft_decel", style = "popin 65%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, bezier = "soft_accel", style = "popin 65%" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 6, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 7, bezier = "soft_decel", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 7, bezier = "soft_decel", style = "slidevert" })
