general {
    lock_cmd = pidof hyprlock || noctalia msg session lock
    before_sleep_cmd = noctalia msg session lock
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = noctalia msg session lock
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
